BATCH_SIZE: 64
LEARNING_RATE: 0.0003
EPOCHS: 50

INPUT_DIM: 256
HIDDEN_DIM: 512
OUTPUT_DIM: 1

DEFAULT_SR: 32000
NOISE_SCALE: 0.1
NOISE_OCCURANCE: 0.5
PERIODIC_NOISE_OCCURANCE: 0.5

MEL_MIN: -80
MEL_MAX: 0

TEST_TRIALS: 1